version: "3"
services:
  application_development:
    build:
      context: ../
      dockerfile: ./provisioning/development.Dockerfile
    environment:
      DB_HOST: database_development
      DB_PORT: 3306
      DB_SCHEMA: genesis_development
      DB_USER: genesis_development
      DB_PASSWORD: genesis_development
      NODE_ENV: development
      PORT: 4000
    entrypoint: [ "./scripts/entrypoint.sh" ]
    expose:
      - "4000"
    ports:
      - "4000:4000"
    depends_on:
      - database_development
  database_development:
    image: mysql:5.7.20
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: genesis_development
      MYSQL_USER: genesis_development
      MYSQL_PASSWORD: genesis_development
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - "../data/db:/var/lib/mysql"
  migrate_development:
    build:
      context: ../
      dockerfile: ./provisioning/development.Dockerfile
    environment:
      DB_HOST: database_development
      DB_PORT: 3306
      DB_SCHEMA: genesis_development
      DB_USER: genesis_development
      DB_PASSWORD: genesis_development
    entrypoint: [ "./scripts/migrate.sh" ]
  seed_development:
    build:
      context: ../
      dockerfile: ./provisioning/development.Dockerfile
    environment:
      DB_HOST: database_development
      DB_PORT: 3306
      DB_SCHEMA: genesis_development
      DB_USER: genesis_development
      DB_PASSWORD: genesis_development
    entrypoint: [ "./scripts/seed.sh" ]
